apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: marketing
  labels:
    app: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        task: marketing
    spec:
      containers:
        - name: marketing
          image: gcr.io/touch-farm/marketing:c5c6a884fd82a2ebc428299ff05ae877ba8ef896
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000