apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: marketing
  labels:
    app: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        task: marketing
    spec:
      containers:
        - name: marketing
          image: gcr.io/touch-farm/marketing:9a62d3b11ee2abc5ae557c588aadf4066870b222
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000